######################################################################
##
## Filename: ALU_tb.udo
## Created on: Sun Feb 23 0:44:05 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
