######################################################################
##
## Filename: glbl.udo
## Created on: Thu Feb 20 14:34:44 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Route Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
