######################################################################
##
## Filename: Reg_array.udo
## Created on: Mon Feb 24 11:54:48 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Route Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
