######################################################################
##
## Filename: Reg_array_tb.udo
## Created on: Mon Feb 24 1:01:28 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
