######################################################################
##
## Filename: tb_Control_Unit.udo
## Created on: Sat Mar 01 18:51:50 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
