######################################################################
##
## Filename: tb_contador.udo
## Created on: Thu Feb 20 12:32:01 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
