######################################################################
##
## Filename: tb_CPU2.udo
## Created on: Tue Mar 04 15:45:39 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
