######################################################################
##
## Filename: tb_Reg_array.udo
## Created on: Mon Feb 24 2:14:12 Hora estándar romance 2025
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
